server:
  # 端口
  port: 8081

spring:
  # 项目名称
  application:
    name: code-generator
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/code_generator
    username: root
    password: 625464

mybatis-plus:
  mapper-locations: classpath*:com/robert/codegenerator/module/mapper/xml/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
#swagger
knife4j:
  #开启增强配置
  enable: true